#define OVERWHITE(type,parent)\
class type: parent {\
    class ItemInfo: UniformItem {\
        mass = 40;\
    };\
}

#define OVERWHITE_UNI(type,parent)\
OVERWHITE(##type##_AOR1,parent);\
OVERWHITE(##type##_AOR2,parent);\
OVERWHITE(##type##_ATT,parent);\
OVERWHITE(##type##_GRY,parent);\
OVERWHITE(##type##_KHK,parent);\
OVERWHITE(##type##_M81,parent);\
OVERWHITE(##type##_MC,parent);\
OVERWHITE(##type##_MCB,parent);\
OVERWHITE(##type##_MCD,parent);\
OVERWHITE(##type##_MCT,parent);\
OVERWHITE(##type##_MCW,parent);\
OVERWHITE(##type##_NAV,parent);\
OVERWHITE(##type##_RGR,parent);\
OVERWHITE(##type##_TSD,parent);\
OVERWHITE(##type##_TSW,parent)

#define OVERWHITE_UNI_FULL(type,parentMM14)\
OVERWHITE(##type##_AOR1,USP_OVERWHITE_G3C);\
OVERWHITE(##type##_AOR2,USP_OVERWHITE_G3C);\
OVERWHITE(##type##_ATT,USP_OVERWHITE_G3C);\
OVERWHITE(##type##_GRY,USP_OVERWHITE_G3C);\
OVERWHITE(##type##_KHK,USP_OVERWHITE_G3C);\
OVERWHITE(##type##_M81,USP_OVERWHITE_G3C);\
OVERWHITE(##type##_MC,USP_OVERWHITE_G3C);\
OVERWHITE(##type##_MCB,USP_OVERWHITE_G3C);\
OVERWHITE(##type##_MCD,USP_OVERWHITE_G3C);\
OVERWHITE(##type##_MCT,USP_OVERWHITE_G3C);\
OVERWHITE(##type##_MCW,USP_OVERWHITE_G3C);\
OVERWHITE(##type##_NAV,USP_OVERWHITE_G3C);\
OVERWHITE(##type##_RGR,USP_OVERWHITE_G3C);\
OVERWHITE(##type##_TSD,USP_OVERWHITE_G3C);\
OVERWHITE(##type##_TSW,USP_OVERWHITE_G3C);\
OVERWHITE(##type##_MM14,parentMM14);\
OVERWHITE(##type##_AMCU,USP_OVERWHITE_G3C_BLK_MM14);\
OVERWHITE(##type##_DCU,USP_OVERWHITE_G3C_BLK_MM14);\
OVERWHITE(##type##_MPD,USP_OVERWHITE_G3C_BLK_MM14);\
OVERWHITE(##type##_MPW,USP_OVERWHITE_G3C_BLK_MM14);\
OVERWHITE(##type##_MTN,USP_OVERWHITE_G3C_BLK_MM14);\
OVERWHITE(##type##_RBS,USP_OVERWHITE_G3C_BLK_MM14);\
OVERWHITE(##type##_UCP,USP_OVERWHITE_G3C_BLK_MM14)


OVERWHITE(USP_OVERWHITE_G3C,Uniform_Base);
OVERWHITE(USP_OVERWHITE_G3C_BLK,USP_OVERWHITE_G3C);
OVERWHITE(USP_OVERWHITE_G3C_GRN,USP_OVERWHITE_G3C);
OVERWHITE(USP_OVERWHITE_G3C_TAN,USP_OVERWHITE_G3C);

OVERWHITE_UNI_FULL(USP_OVERWHITE_G3C_BLK,USP_OVERWHITE_G3C);
OVERWHITE_UNI_FULL(USP_OVERWHITE_G3C_GRN,USP_OVERWHITE_G3C_BLK_MM14);
OVERWHITE_UNI_FULL(USP_OVERWHITE_G3C_MCA,USP_OVERWHITE_G3C_BLK_MM14);
OVERWHITE_UNI_FULL(USP_OVERWHITE_G3C_TAN,USP_OVERWHITE_G3C_BLK_MM14);

OVERWHITE(USP_OVERWHITE_G3C_KP,Uniform_Base);
OVERWHITE_UNI(USP_OVERWHITE_G3C_KP_MCA,USP_OVERWHITE_G3C_KP);

OVERWHITE(USP_OVERWHITE_G3C_KP_MX,Uniform_Base);
OVERWHITE_UNI(USP_OVERWHITE_G3C_KP_MX_MCA,USP_OVERWHITE_G3C_KP_MX);

OVERWHITE(USP_OVERWHITE_G3C_KP_OR,Uniform_Base);
OVERWHITE_UNI(USP_OVERWHITE_G3C_KP_OR_MCA,USP_OVERWHITE_G3C_KP_OR);

OVERWHITE(USP_OVERWHITE_G3C_KP2,USP_OVERWHITE_G3C);
OVERWHITE(USP_OVERWHITE_G3C_KP2_BLK,USP_OVERWHITE_G3C_KP2);
OVERWHITE_UNI(USP_OVERWHITE_G3C_KP2_BLK,USP_OVERWHITE_G3C_KP2);

OVERWHITE(USP_OVERWHITE_G3C_KP2_GRN,USP_OVERWHITE_G3C_KP2);
OVERWHITE_UNI(USP_OVERWHITE_G3C_KP2_GRN,USP_OVERWHITE_G3C_KP2);

OVERWHITE_UNI(USP_OVERWHITE_G3C_KP2_MCA,USP_OVERWHITE_G3C_KP2);

OVERWHITE(USP_OVERWHITE_G3C_KP2_TAN,USP_OVERWHITE_G3C_KP2);
OVERWHITE_UNI(USP_OVERWHITE_G3C_KP2_TAN,USP_OVERWHITE_G3C_KP2);

OVERWHITE(USP_OVERWHITE_G3C_MX,Uniform_Base);
OVERWHITE_UNI(USP_OVERWHITE_G3C_MX_MCA,USP_OVERWHITE_G3C_MX);

OVERWHITE(USP_OVERWHITE_G3C_OR,Uniform_Base);
OVERWHITE_UNI(USP_OVERWHITE_G3C_OR_MCA,USP_OVERWHITE_G3C_OR);
