#define G3C(type,parent)\
class type: parent {\
    class ItemInfo: UniformItem {\
        mass = 40;\
    };\
}

#define G3C_UNI_BASE(type,parent)\
G3C(type,parent);\
G3C(##type##_AOR1,type);\
G3C(##type##_AOR2,type);\
G3C(##type##_GRY,type);\
G3C(##type##_KHK,type);\
G3C(##type##_M81,type);\
G3C(##type##_MC,type);\
G3C(##type##_MCB,type);\
G3C(##type##_MCD,type);\
G3C(##type##_MCT,type);\
G3C(##type##_MCW,type);\
G3C(##type##_NAV,type);\
G3C(##type##_RGR,type);\
G3C(##type##_TSD,type);\
G3C(##type##_TSW,type)

#define G3C_UNI_FULL(type)\
G3C_UNI(type);\
G3C(##type##_AMCU,type);\
G3C(##type##_DCU,type);\
G3C(##type##_MM14,type);\
G3C(##type##_MPD,type);\
G3C(##type##_MPW,type);\
G3C(##type##_MTN,type);\
G3C(##type##_MTP,type);\
G3C(##type##_RBS,type)

#define G3C_UNI(type) G3C_UNI_BASE(type,Uniform_Base)
#define G3C_UNI_PARENT(type) G3C_UNI_BASE(type,USP_G3C)


G3C_UNI_FULL(USP_G3C);
G3C_UNI_FULL(USP_G3C_CS);
G3C_UNI(USP_G3C_CS_CU);
G3C_UNI(USP_G3C_CS_CU_KP);
G3C_UNI(USP_G3C_CS_CU_KP_MX);
G3C_UNI(USP_G3C_CS_CU_KP_MX_VQ);
G3C_UNI(USP_G3C_CS_CU_KP_OR);
G3C_UNI(USP_G3C_CS_CU_KP_OR_VQ);
G3C_UNI(USP_G3C_CS_CU_KP_VQ);
G3C_UNI(USP_G3C_CS_CU_MX);
G3C_UNI(USP_G3C_CS_CU_MX_VQ);
G3C_UNI(USP_G3C_CS_CU_OR);
G3C_UNI(USP_G3C_CS_CU_OR_VQ);
G3C_UNI(USP_G3C_CS_CU_VQ);
G3C_UNI(USP_G3C_CS_KP);
G3C_UNI(USP_G3C_CS_KP_MX);
G3C_UNI(USP_G3C_CS_KP_OR);
G3C_UNI(USP_G3C_CS_KP_OR_VQ);
G3C_UNI(USP_G3C_CS_KP_VQ);
G3C_UNI(USP_G3C_CS_MX);
G3C_UNI(USP_G3C_CS_MX_VQ);
G3C_UNI(USP_G3C_CS_OR);
G3C_UNI(USP_G3C_CS_OR_VQ);
G3C_UNI(USP_G3C_CS_VQ);

G3C_UNI_PARENT(USP_G3C_CU);
G3C_UNI_PARENT(USP_G3C_CU_KP);
G3C_UNI_PARENT(USP_G3C_CU_KP_MX);
G3C_UNI_PARENT(USP_G3C_CU_KP_OR);
G3C_UNI_PARENT(USP_G3C_CU_MX);
G3C_UNI_PARENT(USP_G3C_CU_OR);
G3C_UNI_PARENT(USP_G3C_KP);
G3C_UNI_PARENT(USP_G3C_KP_MX);
G3C_UNI_PARENT(USP_G3C_KP_OR);
G3C_UNI_PARENT(USP_G3C_MX);
G3C_UNI_PARENT(USP_G3C_MX_VQ);
G3C_UNI_PARENT(USP_G3C_OR);
G3C_UNI_PARENT(USP_G3C_OR_VQ);
G3C_UNI_PARENT(USP_G3C_VQ);

G3C_UNI_FULL(USP_G3C_RS);
G3C_UNI(USP_G3C_RS_CU);
G3C_UNI(USP_G3C_RS_CU_KP);
G3C_UNI(USP_G3C_RS_CU_KP_MX);
G3C_UNI(USP_G3C_RS_CU_KP_MX_VQ);
G3C_UNI(USP_G3C_RS_CU_KP_OR);
G3C_UNI(USP_G3C_RS_CU_KP_OR_VQ);
G3C_UNI(USP_G3C_RS_CU_KP_VQ);
G3C_UNI(USP_G3C_RS_CU_MX);
G3C_UNI(USP_G3C_RS_CU_MX_VQ);
G3C_UNI(USP_G3C_RS_CU_OR);
G3C_UNI(USP_G3C_RS_CU_OR_VQ);
G3C_UNI(USP_G3C_RS_CU_VQ);
G3C_UNI(USP_G3C_RS_KP);
G3C_UNI(USP_G3C_RS_KP_MX);
G3C_UNI(USP_G3C_RS_KP_OR);
G3C_UNI(USP_G3C_RS_KP_OR_VQ);
G3C_UNI(USP_G3C_RS_KP_VQ);
G3C_UNI(USP_G3C_RS_MX);
G3C_UNI(USP_G3C_RS_MX_VQ);
G3C_UNI(USP_G3C_RS_OR);
G3C_UNI(USP_G3C_RS_OR_VQ);
G3C_UNI(USP_G3C_RS_VQ);

G3C_UNI_FULL(USP_G3C_RS2);
G3C_UNI(USP_G3C_RS2_CU);
G3C_UNI(USP_G3C_RS2_CU_KP);
G3C_UNI(USP_G3C_RS2_CU_KP_MX);
G3C_UNI(USP_G3C_RS2_CU_KP_MX_VQ);
G3C_UNI(USP_G3C_RS2_CU_KP_OR);
G3C_UNI(USP_G3C_RS2_CU_KP_OR_VQ);
G3C_UNI(USP_G3C_RS2_CU_KP_VQ);
G3C_UNI(USP_G3C_RS2_CU_MX);
G3C_UNI(USP_G3C_RS2_CU_MX_VQ);
G3C_UNI(USP_G3C_RS2_CU_OR);
G3C_UNI(USP_G3C_RS2_CU_OR_VQ);
G3C_UNI(USP_G3C_RS2_CU_VQ);
G3C_UNI(USP_G3C_RS2_KP);
G3C_UNI(USP_G3C_RS2_KP_MX);
G3C_UNI(USP_G3C_RS2_KP_OR);
G3C_UNI(USP_G3C_RS2_KP_OR_VQ);
G3C_UNI(USP_G3C_RS2_KP_VQ);
G3C_UNI(USP_G3C_RS2_MX);
G3C_UNI(USP_G3C_RS2_MX_VQ);
G3C_UNI(USP_G3C_RS2_OR);
G3C_UNI(USP_G3C_RS2_OR_VQ);

G3C_UNI_FULL(USP_G3C_IST);
G3C_UNI(USP_G3C_IST_KP);
G3C_UNI(USP_G3C_IST_KP_MX);
G3C_UNI(USP_G3C_IST_KP_OR);
G3C_UNI(USP_G3C_IST_MX);
G3C_UNI(USP_G3C_IST_OR);
G3C_UNI(USP_G3C_RS_OR_VQ);
G3C_UNI(USP_G3C_RS_VQ);
G3C_UNI(USP_G3C_RS_VQ);
G3C_UNI(USP_G3C_RS_OR);
G3C_UNI(USP_G3C_RS_OR_VQ);
G3C_UNI(USP_G3C_RS_VQ);
