name = "Weapons-Balance-USP"
prefix = "wb_usp"
author = "johnb43"
template = "cba"
mainprefix = "z"
files = [
    "CHANGELOG.md",
    "mod.cpp",
    "LICENSE",
    "README.md"
]
folder_optionals = false
sig_version = 3
