#define CRYE(type)\
class type: H_HelmetB {\
    class ItemInfo: HeadgearItem {\
        class HitpointsProtectionInfo {\
            class Head {\
                armor = 6;\
                hitpointName = "HitHead";\
                passThrough = 0.5;\
            };\
        };\
    };\
}

CRYE(USP_CRYE_AIRFRAME_CMWGUISV);
CRYE(USP_CRYE_AIRFRAME_CMWGUIS);
CRYE(USP_CRYE_AIRFRAME_CMWGUITV);
CRYE(USP_CRYE_AIRFRAME_CMWGUIT);
CRYE(USP_CRYE_AIRFRAME_CMWGUIV);
CRYE(USP_CRYE_AIRFRAME_CMWGUI);
CRYE(USP_CRYE_AIRFRAME_CMWGUSV);
CRYE(USP_CRYE_AIRFRAME_CMWGUS);
CRYE(USP_CRYE_AIRFRAME_CMWGUTV);
CRYE(USP_CRYE_AIRFRAME_CMWGUT);
CRYE(USP_CRYE_AIRFRAME_CMWGUV);
CRYE(USP_CRYE_AIRFRAME_CMWGU);
CRYE(USP_CRYE_AIRFRAME_CMWISV);
CRYE(USP_CRYE_AIRFRAME_CMWIS);
CRYE(USP_CRYE_AIRFRAME_CMWITV);
CRYE(USP_CRYE_AIRFRAME_CMWIT);
CRYE(USP_CRYE_AIRFRAME_CMWIV);
CRYE(USP_CRYE_AIRFRAME_CMWI);
CRYE(USP_CRYE_AIRFRAME_CMWSV);
CRYE(USP_CRYE_AIRFRAME_CMWS);
CRYE(USP_CRYE_AIRFRAME_CMWTV);
CRYE(USP_CRYE_AIRFRAME_CMWT);
CRYE(USP_CRYE_AIRFRAME_CMWV);
CRYE(USP_CRYE_AIRFRAME_CMW);

CRYE(USP_CRYE_AIRFRAME_CMGUISV);
CRYE(USP_CRYE_AIRFRAME_CMGUIS);
CRYE(USP_CRYE_AIRFRAME_CMGUITV);
CRYE(USP_CRYE_AIRFRAME_CMGUIT);
CRYE(USP_CRYE_AIRFRAME_CMGUIV);
CRYE(USP_CRYE_AIRFRAME_CMGUI);
CRYE(USP_CRYE_AIRFRAME_CMGUSV);
CRYE(USP_CRYE_AIRFRAME_CMGUS);
CRYE(USP_CRYE_AIRFRAME_CMGUTV);
CRYE(USP_CRYE_AIRFRAME_CMGUT);
CRYE(USP_CRYE_AIRFRAME_CMGUV);
CRYE(USP_CRYE_AIRFRAME_CMGU);

CRYE(USP_CRYE_AIRFRAME_CMISV);
CRYE(USP_CRYE_AIRFRAME_CMIS);
CRYE(USP_CRYE_AIRFRAME_CMITV);
CRYE(USP_CRYE_AIRFRAME_CMIT);
CRYE(USP_CRYE_AIRFRAME_CMIV);
CRYE(USP_CRYE_AIRFRAME_CMI);
CRYE(USP_CRYE_AIRFRAME_CMSV);
CRYE(USP_CRYE_AIRFRAME_CMS);
CRYE(USP_CRYE_AIRFRAME_CMTV);
CRYE(USP_CRYE_AIRFRAME_CMT);
CRYE(USP_CRYE_AIRFRAME_CMV);

CRYE(USP_CRYE_AIRFRAME_CWGUISV);
CRYE(USP_CRYE_AIRFRAME_CWGUIS);
CRYE(USP_CRYE_AIRFRAME_CWGUITV);
CRYE(USP_CRYE_AIRFRAME_CWGUIT);
CRYE(USP_CRYE_AIRFRAME_CWGUIV);
CRYE(USP_CRYE_AIRFRAME_CWGUI);
CRYE(USP_CRYE_AIRFRAME_CWGUSV);
CRYE(USP_CRYE_AIRFRAME_CWGUS);
CRYE(USP_CRYE_AIRFRAME_CWGUTV);
CRYE(USP_CRYE_AIRFRAME_CWGUT);
CRYE(USP_CRYE_AIRFRAME_CWGU);

CRYE(USP_CRYE_AIRFRAME_CWISV);
CRYE(USP_CRYE_AIRFRAME_CWIS);
CRYE(USP_CRYE_AIRFRAME_CWITV);
CRYE(USP_CRYE_AIRFRAME_CWIT);
CRYE(USP_CRYE_AIRFRAME_CWIV);
CRYE(USP_CRYE_AIRFRAME_CWI);
CRYE(USP_CRYE_AIRFRAME_CWSV);
CRYE(USP_CRYE_AIRFRAME_CWS);
CRYE(USP_CRYE_AIRFRAME_CWTV);
CRYE(USP_CRYE_AIRFRAME_CWT);
CRYE(USP_CRYE_AIRFRAME_CWV);
CRYE(USP_CRYE_AIRFRAME_CW);

CRYE(USP_CRYE_AIRFRAME_GUISV);
CRYE(USP_CRYE_AIRFRAME_GUIS);
CRYE(USP_CRYE_AIRFRAME_GUITV);
CRYE(USP_CRYE_AIRFRAME_GUIT);
CRYE(USP_CRYE_AIRFRAME_GUIV);
CRYE(USP_CRYE_AIRFRAME_GUI);
CRYE(USP_CRYE_AIRFRAME_GUSV);
CRYE(USP_CRYE_AIRFRAME_GUS);
CRYE(USP_CRYE_AIRFRAME_GUTV);
CRYE(USP_CRYE_AIRFRAME_GUT);
CRYE(USP_CRYE_AIRFRAME_GUV);
CRYE(USP_CRYE_AIRFRAME_GU);

CRYE(USP_CRYE_AIRFRAME_IRSV);
CRYE(USP_CRYE_AIRFRAME_IRS);
CRYE(USP_CRYE_AIRFRAME_IRTV);
CRYE(USP_CRYE_AIRFRAME_IRT);
CRYE(USP_CRYE_AIRFRAME_IRV);
CRYE(USP_CRYE_AIRFRAME_IR);
CRYE(USP_CRYE_AIRFRAME_SFV);
CRYE(USP_CRYE_AIRFRAME_SF);
CRYE(USP_CRYE_AIRFRAME_TLV);
CRYE(USP_CRYE_AIRFRAME_TL);
CRYE(USP_CRYE_AIRFRAME_VL);
