class USP_MICH_TC2000: H_HelmetB {
    class ItemInfo: ItemInfo {
        mass = 40;
    };
};
class USP_MICH_TC2000_CT: H_HelmetB {
    class ItemInfo: ItemInfo {
        mass = 40;
    };
};
class USP_HEAD_MICH_TC2002_TAN: H_HelmetB {
    class ItemInfo: ItemInfo {
        mass = 40;
    };
};

#define MICH_NO_EAR(type)\
class type: USP_MICH_TC2000 {\
    class ItemInfo: HeadgearItem {\
        mass = 40;\
        class HitpointsProtectionInfo {\
            class Head {\
                armor = 6;\
                hitpointName = "HitHead";\
                passThrough = 0.5;\
            };\
        };\
    };\
}

#define MICH(type)\
class type: USP_MICH_TC2000 {\
    ace_hearing_lowerVolume = 0;\
    ace_hearing_protection = 0.8;\
    class ItemInfo: HeadgearItem {\
        mass = 40;\
        class HitpointsProtectionInfo {\
            class Head {\
                armor = 6;\
                hitpointName = "HitHead";\
                passThrough = 0.5;\
            };\
        };\
    };\
}

MICH(USP_MICH_TC2000_CT_CM_GB_IR_PH_RM);
MICH(USP_MICH_TC2000_CT_CM_GB_IR_PH);
MICH(USP_MICH_TC2000_CT_CM_GB_IR_PS);
MICH(USP_MICH_TC2000_CT_CM_GB_IR_RM_PS);
MICH(USP_MICH_TC2000_CT_CM_GB_IR_RM_SF);
MICH(USP_MICH_TC2000_CT_CM_GB_IR_RM);
MICH(USP_MICH_TC2000_CT_CM_GB_IR_SF);
MICH(USP_MICH_TC2000_CT_CM_GB_IR);
MICH(USP_MICH_TC2000_CT_CM_GB_PH_RM_VL);
MICH(USP_MICH_TC2000_CT_CM_GB_PH_RM);
MICH(USP_MICH_TC2000_CT_CM_GB_PH_VL);
MICH(USP_MICH_TC2000_CT_CM_GB_PH);
MICH(USP_MICH_TC2000_CT_CM_GB_PS);
MICH(USP_MICH_TC2000_CT_CM_GB_PS_VL);
MICH(USP_MICH_TC2000_CT_CM_GB_RM_PS_VL);
MICH(USP_MICH_TC2000_CT_CM_GB_RM_PS);
MICH(USP_MICH_TC2000_CT_CM_GB_RM_SF_VL);
MICH(USP_MICH_TC2000_CT_CM_GB_RM_SF);
MICH(USP_MICH_TC2000_CT_CM_GB_RM_VL);
MICH(USP_MICH_TC2000_CT_CM_GB_RM);
MICH(USP_MICH_TC2000_CT_CM_GB_SF_VL);
MICH(USP_MICH_TC2000_CT_CM_GB_SF);
MICH(USP_MICH_TC2000_CT_CM_GB_VL);
MICH(USP_MICH_TC2000_CT_CM_GB);

MICH(USP_MICH_TC2000_CT_CM_GC_IB_PH_VL);
MICH(USP_MICH_TC2000_CT_CM_GC_IB_PH);
MICH(USP_MICH_TC2000_CT_CM_GC_IB_PS_VL);
MICH(USP_MICH_TC2000_CT_CM_GC_IB_PS);
MICH(USP_MICH_TC2000_CT_CM_GC_IB_SF_VL);
MICH(USP_MICH_TC2000_CT_CM_GC_IB_SF);
MICH(USP_MICH_TC2000_CT_CM_GC_IB_VL);
MICH(USP_MICH_TC2000_CT_CM_GC_IB);
MICH(USP_MICH_TC2000_CT_CM_GC_IR_NS_PH);
MICH(USP_MICH_TC2000_CT_CM_GC_IR_NS);
MICH(USP_MICH_TC2000_CT_CM_GC_IR_PH);
MICH(USP_MICH_TC2000_CT_CM_GC_IR_PS);
MICH(USP_MICH_TC2000_CT_CM_GC_IR_SF);
MICH(USP_MICH_TC2000_CT_CM_GC_IR);
MICH(USP_MICH_TC2000_CT_CM_GC_NS_PH);
MICH(USP_MICH_TC2000_CT_CM_GC_NS_PS);
MICH(USP_MICH_TC2000_CT_CM_GC_NS_SF);
MICH(USP_MICH_TC2000_CT_CM_GC_NS);
MICH(USP_MICH_TC2000_CT_CM_GC_PH_VL);
MICH(USP_MICH_TC2000_CT_CM_GC_PH);
MICH(USP_MICH_TC2000_CT_CM_GC_PS_VL);
MICH(USP_MICH_TC2000_CT_CM_GC_PS);
MICH(USP_MICH_TC2000_CT_CM_GC_SF_VL);
MICH(USP_MICH_TC2000_CT_CM_GC_SF);
MICH(USP_MICH_TC2000_CT_CM_GC_VL);
MICH(USP_MICH_TC2000_CT_CM_GC);

MICH(USP_MICH_TC2000_CT_CM_GG);
MICH(USP_MICH_TC2000_CT_CM_GU);
MICH(USP_MICH_TC2000_CT_CM_IB);
MICH(USP_MICH_TC2000_CT_CM_IR);
MICH(USP_MICH_TC2000_CT_CM_LP);
MICH(USP_MICH_TC2000_CT_CM_NS);
MICH(USP_MICH_TC2000_CT_CM_PC_GB_IR_RM);
MICH(USP_MICH_TC2000_CT_CM_PC_GB_IR);
MICH(USP_MICH_TC2000_CT_CM_PC_GB_NS_RM);
MICH(USP_MICH_TC2000_CT_CM_PC_GB_NS);
MICH(USP_MICH_TC2000_CT_CM_PC_GB_RM_VL);
MICH(USP_MICH_TC2000_CT_CM_PC_GB_RM);
MICH(USP_MICH_TC2000_CT_CM_PC_GB_VL);
MICH(USP_MICH_TC2000_CT_CM_PC_GB);
MICH(USP_MICH_TC2000_CT_CM_PC_GC_IB_VL);
MICH(USP_MICH_TC2000_CT_CM_PC_GC_IB);
MICH(USP_MICH_TC2000_CT_CM_PC_GC_IR);
MICH(USP_MICH_TC2000_CT_CM_PC_GC_NS);
MICH(USP_MICH_TC2000_CT_CM_PC_GC_VL);
MICH(USP_MICH_TC2000_CT_CM_PC_GC);

MICH(USP_MICH_TC2000_CT_CM_PC_GG_GB_IB_RM_VL);
MICH(USP_MICH_TC2000_CT_CM_PC_GG_GB_IB_RM);
MICH(USP_MICH_TC2000_CT_CM_PC_GG_GB_IB_VL);
MICH(USP_MICH_TC2000_CT_CM_PC_GG_GB_IB);
MICH(USP_MICH_TC2000_CT_CM_PC_GG_GB_IR_RM);
MICH(USP_MICH_TC2000_CT_CM_PC_GG_GB_IR);
MICH(USP_MICH_TC2000_CT_CM_PC_GG_GB_RM);
MICH(USP_MICH_TC2000_CT_CM_PC_GG_GB_VL);
MICH(USP_MICH_TC2000_CT_CM_PC_GG_GB);
MICH(USP_MICH_TC2000_CT_CM_PC_GG_IB_RM_VL);
MICH(USP_MICH_TC2000_CT_CM_PC_GG_IB_RM);
MICH(USP_MICH_TC2000_CT_CM_PC_GG_IB_VL);
MICH(USP_MICH_TC2000_CT_CM_PC_GG_IB);
MICH(USP_MICH_TC2000_CT_CM_PC_GG_IR_RM);
MICH(USP_MICH_TC2000_CT_CM_PC_GG_IR);
MICH(USP_MICH_TC2000_CT_CM_PC_GG_NS_RM);
MICH(USP_MICH_TC2000_CT_CM_PC_GG_NS);
MICH(USP_MICH_TC2000_CT_CM_PC_GG_RM_VL);
MICH(USP_MICH_TC2000_CT_CM_PC_GG_RM);
MICH(USP_MICH_TC2000_CT_CM_PC_GG_VL);
MICH(USP_MICH_TC2000_CT_CM_PC_GG);

MICH(USP_MICH_TC2000_CT_CM_PC_GU_IB_RM_VL);
MICH(USP_MICH_TC2000_CT_CM_PC_GU_IB_RM);
MICH(USP_MICH_TC2000_CT_CM_PC_GU_IB_VL);
MICH(USP_MICH_TC2000_CT_CM_PC_GU_IB);
MICH(USP_MICH_TC2000_CT_CM_PC_GU_IR_NS_RM);
MICH(USP_MICH_TC2000_CT_CM_PC_GU_IR_NS);
MICH(USP_MICH_TC2000_CT_CM_PC_GU_IR_RM);
MICH(USP_MICH_TC2000_CT_CM_PC_GU_IR);
MICH(USP_MICH_TC2000_CT_CM_PC_GU_NS_RM);
MICH(USP_MICH_TC2000_CT_CM_PC_GU_NS);
MICH(USP_MICH_TC2000_CT_CM_PC_GU_RM_VL);
MICH(USP_MICH_TC2000_CT_CM_PC_GU_RM);
MICH(USP_MICH_TC2000_CT_CM_PC_GU_VL);
MICH(USP_MICH_TC2000_CT_CM_PC_GU);
MICH(USP_MICH_TC2000_CT_CM_PC_IB_RM_VL);
MICH(USP_MICH_TC2000_CT_CM_PC_IB_RM);
MICH(USP_MICH_TC2000_CT_CM_PC_IB_VL);
MICH(USP_MICH_TC2000_CT_CM_PC_IB);
MICH(USP_MICH_TC2000_CT_CM_PC_IR_NS_RM);
MICH(USP_MICH_TC2000_CT_CM_PC_IR_NS);
MICH(USP_MICH_TC2000_CT_CM_PC_IR_RM);
MICH(USP_MICH_TC2000_CT_CM_PC_IR);
MICH(USP_MICH_TC2000_CT_CM_PC_LP_IB_RM_VL);
MICH(USP_MICH_TC2000_CT_CM_PC_LP_IB_RM);
MICH(USP_MICH_TC2000_CT_CM_PC_LP_IB_VL);
MICH(USP_MICH_TC2000_CT_CM_PC_LP_IB);
MICH(USP_MICH_TC2000_CT_CM_PC_LP_IR_NS_RM);
MICH(USP_MICH_TC2000_CT_CM_PC_LP_IR_NS);
MICH(USP_MICH_TC2000_CT_CM_PC_LP_IR_RM);
MICH(USP_MICH_TC2000_CT_CM_PC_LP_IR);
MICH(USP_MICH_TC2000_CT_CM_PC_LP_NS_RM);
MICH(USP_MICH_TC2000_CT_CM_PC_LP_NS);
MICH(USP_MICH_TC2000_CT_CM_PC_LP_RM_VL);
MICH(USP_MICH_TC2000_CT_CM_PC_LP_RM);
MICH(USP_MICH_TC2000_CT_CM_PC_LP_VL);
MICH(USP_MICH_TC2000_CT_CM_PC_LP);
MICH(USP_MICH_TC2000_CT_CM_PC_NS_RM);
MICH(USP_MICH_TC2000_CT_CM_PC_NS);
MICH(USP_MICH_TC2000_CT_CM_PC_RM_VL);
MICH(USP_MICH_TC2000_CT_CM_PC_RM);
MICH(USP_MICH_TC2000_CT_CM_PC_VL);
MICH(USP_MICH_TC2000_CT_CM_PC);

MICH(USP_MICH_TC2000_CT_CM_PH);
MICH(USP_MICH_TC2000_CT_CM_PS);
MICH(USP_MICH_TC2000_CT_CM_RM);
MICH(USP_MICH_TC2000_CT_CM_SF);
MICH(USP_MICH_TC2000_CT_CM_VL);
MICH(USP_MICH_TC2000_CT_CM);
MICH(USP_MICH_TC2000_CT_GB);
MICH(USP_MICH_TC2000_CT_GC);
MICH(USP_MICH_TC2000_CT_GG);
MICH(USP_MICH_TC2000_CT_GU);
MICH(USP_MICH_TC2000_CT_IB);
MICH(USP_MICH_TC2000_CT_IR);
MICH(USP_MICH_TC2000_CT_LP);
MICH(USP_MICH_TC2000_CT_MC);
MICH(USP_MICH_TC2000_CT_NS);
MICH(USP_MICH_TC2000_CT_PC);
MICH(USP_MICH_TC2000_CT_PH);
MICH(USP_MICH_TC2000_CT_PS);
MICH(USP_MICH_TC2000_CT_RM);
MICH(USP_MICH_TC2000_CT_SF);
MICH(USP_MICH_TC2000_CT_VL);

MICH_NO_EAR(USP_MICH_TC2000_CM);
MICH_NO_EAR(USP_MICH_TC2000_GB);
MICH_NO_EAR(USP_MICH_TC2000_GC);
MICH_NO_EAR(USP_MICH_TC2000_GG);
MICH_NO_EAR(USP_MICH_TC2000_GU);
MICH_NO_EAR(USP_MICH_TC2000_IB);
MICH_NO_EAR(USP_MICH_TC2000_IR);
MICH_NO_EAR(USP_MICH_TC2000_LP);
MICH_NO_EAR(USP_MICH_TC2000_MC);
MICH_NO_EAR(USP_MICH_TC2000_NS);
MICH_NO_EAR(USP_MICH_TC2000_PC);
MICH_NO_EAR(USP_MICH_TC2000_PH);
MICH_NO_EAR(USP_MICH_TC2000_PS);
MICH_NO_EAR(USP_MICH_TC2000_RM);
MICH_NO_EAR(USP_MICH_TC2000_S2);
MICH_NO_EAR(USP_MICH_TC2000_S3);
MICH_NO_EAR(USP_MICH_TC2000_SF);
MICH_NO_EAR(USP_MICH_TC2000_VL);
